# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

FROM nginx
COPY nginx.conf /etc/nginx/templates/default.conf.template
COPY cert.crt /etc/nginx/cert.crt
COPY cert.key /etc/nginx/cert.key
